package xj.mobile.tool

import xj.mobile.lang.*

class GenerateUITypes {  

  static main(args) { 
	def typeNames = Language.definitions.keySet()
	generateUIClass(typeNames)
  }

  static generateUIClass(typeNames) { 
	String packageName = 'xj.mobile.lang.madl'
	String className = 'UITypes'

	def file = "src/${packageName.replace('.', '/')}/${className}.groovy"
	println "Write ${file}"

	def body = typeNames.collect{ name -> 
	  "class ${name} { }"
	}.join('\n\n')
	
	def code = """package ${packageName}

/*
 *  Generated by xj.mobile.tool.GenerateUITypes
 *  Created on: ${new Date()}
 */

${body} 
"""

	new File(file).write(code)
  }

}