package xj.mobile.lang.madl

/*
 *  Generated by xj.mobile.tool.GenerateUITypes
 *  Created on: Tue May 07 15:37:26 CDT 2013
 */

class View { }

class TabbedView { }

class NavigationView { }

class ListView { }

class Alert { }

class Popup { }

class Menu { }

class DatePickerDialog { }

class TimePickerDialog { }

class Panel { }

class Box { }

class Table { }

class Row { }

class Section { }

class Label { }

class Image { }

class Button { }

class Text { }

class Switch { }

class Slider { }

class Selection { }

class NumberStepper { }

class CheckBox { }

class RadioButton { }

class RadioGroup { }

class ProgressBar { }

class Picker { }

class DatePicker { }

class TimePicker { }

class Item { }

class Web { }

class Map { }

class Annotation { }

class Toast { }

class PageView { }

class DateTimePicker { }

class PageControl { }

class Page { }

class ExpandableListView { }

class Spinner { }

class SpinnerGroup { } 

