package xj.mobile.model.properties

/*
 *  Generated by xj.mobile.tool.ProcessType
 *  Created on: Fri May 17 11:14:05 CDT 2013
 */
class InterfaceOrientations extends Property { 

  static values = [:]
  static names = [ 'Unknown', 'Portrait', 'PortraitUpsideDown', 'LandscapeLeft', 'LandscapeRight', 'FaceUp', 'FaceDown' ]

  static final InterfaceOrientations Portrait = new InterfaceOrientations('Portrait')
  static final InterfaceOrientations PortraitUpsideDown = new InterfaceOrientations('PortraitUpsideDown')
  static final InterfaceOrientations LandscapeLeft = new InterfaceOrientations('LandscapeLeft')
  static final InterfaceOrientations LandscapeRight = new InterfaceOrientations('LandscapeRight')

  String name
  
  private InterfaceOrientations(name) { 
    this.name = name
    values[name] = this
  }

  String toIOSString() { 
    "UIInterfaceOrientation${name}"
  }

  String toShortString() { 
    name
  }

  String toString() { 
    "InterfaceOrientations.${name}"
  }

  static boolean isCompatible(value) { 
	(value instanceof String) || 
	(value instanceof List) 
  }

  static boolean hasValue(name) { 
    values.hasKey(name)
  }

  static InterfaceOrientations getValue(name) { 
    values[name]
  }

}
