package xj.mobile.model.properties

/*
 *  Generated by xj.mobile.tool.ProcessType
 *  Created on: Wed Jul 17 14:24:21 CDT 2013
 */
class KeyboardType extends Property { 

  static values = [:]
  static names = [ 'Default', 'ASCIICapable', 'NumbersAndPunctuation', 'URL', 'NumberPad', 'PhonePad', 'NamePhonePad', 'EmailAddress', 'DecimalPad', 'Twitter', 'Alphabet' ]

  static final KeyboardType Default = new KeyboardType('Default')
  static final KeyboardType ASCIICapable = new KeyboardType('ASCIICapable')
  static final KeyboardType NumbersAndPunctuation = new KeyboardType('NumbersAndPunctuation')
  static final KeyboardType URL = new KeyboardType('URL')
  static final KeyboardType NumberPad = new KeyboardType('NumberPad')
  static final KeyboardType PhonePad = new KeyboardType('PhonePad')
  static final KeyboardType NamePhonePad = new KeyboardType('NamePhonePad')
  static final KeyboardType EmailAddress = new KeyboardType('EmailAddress')
  static final KeyboardType DecimalPad = new KeyboardType('DecimalPad')
  static final KeyboardType Twitter = new KeyboardType('Twitter')
  static final KeyboardType Alphabet = new KeyboardType('Alphabet')

  String name
  
  private KeyboardType(name) { 
    this.name = name
    values[name] = this
  }

  String toIOSString() { 
    "UIKeyboardType${name}"
  }

  String toAndroidJavaString() { 
    "KeyboardType${name}"
  }

  String toShortString() { 
    name
  }

  String toString() { 
    "KeyboardType.${name}"
  }

  static boolean isCompatible(value) { 
	(value instanceof String) || 
	(value instanceof List) 
  }

  static boolean hasValue(name) { 
    values.hasKey(name)
  }

  static KeyboardType getValue(name) { 
    values[name]
  }

}
