package xj.mobile.model.properties

/*
 *  Generated by xj.mobile.tool.ProcessType
 *  Created on: Wed Jul 17 14:24:21 CDT 2013
 */
class ModalTransitionStyle extends Property { 

  static values = [:]
  static names = [ 'CoverVertical', 'FlipHorizontal', 'CrossDissolve', 'PartialCurl' ]

  static final ModalTransitionStyle CoverVertical = new ModalTransitionStyle('CoverVertical')
  static final ModalTransitionStyle FlipHorizontal = new ModalTransitionStyle('FlipHorizontal')
  static final ModalTransitionStyle CrossDissolve = new ModalTransitionStyle('CrossDissolve')
  static final ModalTransitionStyle PartialCurl = new ModalTransitionStyle('PartialCurl')

  String name
  
  private ModalTransitionStyle(name) { 
    this.name = name
    values[name] = this
  }

  String toIOSString() { 
    "UIModalTransitionStyle${name}"
  }

  String toAndroidJavaString() { 
    "ModalTransitionStyle${name}"
  }

  String toShortString() { 
    name
  }

  String toString() { 
    "ModalTransitionStyle.${name}"
  }

  static boolean isCompatible(value) { 
	(value instanceof String) || 
	(value instanceof List) 
  }

  static boolean hasValue(name) { 
    values.hasKey(name)
  }

  static ModalTransitionStyle getValue(name) { 
    values[name]
  }

}
